-- Add AI summary column to jira_issues table
-- This will store human-friendly summaries generated by Claude

ALTER TABLE jira_issues
ADD COLUMN IF NOT EXISTS ai_summary TEXT;

COMMENT ON COLUMN jira_issues.ai_summary IS 'Human-friendly summary generated by Claude AI for customer success managers';

-- Verify the column was added
SELECT column_name, data_type, is_nullable
FROM information_schema.columns
WHERE table_name = 'jira_issues' AND column_name = 'ai_summary';
