-- Seed account_jira_links from Looker ground-truth export
-- Source: "Top 24(ish) Dashboard" Looker exports (both Bug and All Issues views)
-- These links are derived from Salesforce Case → Jira ticket joins in Looker,
-- representing the authoritative mapping of Jira tickets to customer accounts.
-- match_type = 'looker_export', confidence = 1.0

-- We join on jira_issues.jira_key and accounts.name to get the UUIDs,
-- then upsert into account_jira_links.

INSERT INTO account_jira_links (user_id, account_id, jira_issue_id, match_type, match_confidence)
SELECT DISTINCT
  ji.user_id,
  a.id AS account_id,
  ji.id AS jira_issue_id,
  'looker_export' AS match_type,
  1.0 AS match_confidence
FROM (VALUES
  ('BUGS-11164','The Storage Mall - CORP.'),
  ('BUGS-11180','Spartan Investment Group - CORP.'),
  ('BUGS-11220','The Storage Mall - CORP.'),
  ('BUGS-11375','West Coast Self-Storage - CORP.'),
  ('BUGS-11606','Go Store It Management LLC - CORP'),
  ('BUGS-11767','Attic Management Group - CORP'),
  ('BUGS-11791','Spartan Investment Group - CORP.'),
  ('BUGS-11796','Go Store It Management LLC - CORP'),
  ('BUGS-11813','West Coast Self-Storage - CORP.'),
  ('BUGS-11819','Attic Management Group - CORP'),
  ('BUGS-11827','West Coast Self-Storage - CORP.'),
  ('BUGS-11829','White Label Storage Management - CORP'),
  ('BUGS-11850','White Label Storage Management - CORP'),
  ('BUGS-11858','StoreEase - CORP'),
  ('BUGS-11861','West Coast Self-Storage - CORP.'),
  ('BUGS-11937','West Coast Self-Storage - CORP.'),
  ('BUGS-11985','SHS Development Company dba The Lock Up Self Storage - CORP.'),
  ('BUGS-11991','Andover Properties - Storage King USA - CORP.'),
  ('BUGS-12000','National Storage Management - CORP'),
  ('BUGS-12069','Spartan Investment Group - CORP.'),
  ('BUGS-12080','Andover Properties - Storage King USA - CORP.'),
  ('BUGS-6777','Storage Asset Management - CORP'),
  ('BUGS-7787','Storage Asset Management - CORP'),
  ('CAL-10095','Andover Properties - Storage King USA - CORP.'),
  ('CAL-10432','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('CAL-10432','Prime Group Holdings, LLC - CORP'),
  ('CAL-9808','Andover Properties - Storage King USA - CORP.'),
  ('CAL-9855','National Storage Management - CORP'),
  ('CAL-9855','Prime Group Holdings, LLC - CORP'),
  ('CPBUG-1193','National Storage Management - CORP'),
  ('CPBUG-1253','Prime Group Holdings, LLC - CORP'),
  ('CPBUG-1303','Prime Group Holdings, LLC - CORP'),
  ('CPBUG-1445','Prime Group Holdings, LLC - CORP'),
  ('CPBUG-734','Prime Group Holdings, LLC - CORP'),
  ('CPBUG-980','Prime Group Holdings, LLC - CORP'),
  ('CRM-11','Spartan Investment Group - CORP.'),
  ('CRM-17','Prime Group Holdings, LLC - CORP'),
  ('CRM-2064','Andover Properties - Storage King USA - CORP.'),
  ('CRM-2066','Prime Group Holdings, LLC - CORP'),
  ('CRM-2066','Spartan Investment Group - CORP.'),
  ('CRM-2079','Prime Group Holdings, LLC - CORP'),
  ('CRM-2084','Andover Properties - Storage King USA - CORP.'),
  ('CRM-2084','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('CRM-2084','National Storage Management - CORP'),
  ('CRM-2084','New Crescendo LLC - CORP'),
  ('CRM-2084','Prime Group Holdings, LLC - CORP'),
  ('CRM-2084','Spartan Investment Group - CORP.'),
  ('CRM-2085','Andover Properties - Storage King USA - CORP.'),
  ('CRM-2099','National Storage Management - CORP'),
  ('CRM-2100','Prime Group Holdings, LLC - CORP'),
  ('CRM-2101','Prime Group Holdings, LLC - CORP'),
  ('CRM-2103','Andover Properties - Storage King USA - CORP.'),
  ('CRM-2103','Prime Group Holdings, LLC - CORP'),
  ('CRM-2104','Andover Properties - Storage King USA - CORP.'),
  ('CRM-2104','Prime Group Holdings, LLC - CORP'),
  ('CRM-2129','Andover Properties - Storage King USA - CORP.'),
  ('CRM-2133','Andover Properties - Storage King USA - CORP.'),
  ('CRM-2136','Andover Properties - Storage King USA - CORP.'),
  ('CRM-2136','Prime Group Holdings, LLC - CORP'),
  ('CRM-2148','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('CRM-2148','National Storage Management - CORP'),
  ('CRM-2148','Prime Group Holdings, LLC - CORP'),
  ('CRM-2150','Andover Properties - Storage King USA - CORP.'),
  ('CRM-2175','Elite-Stor Storage - CORP'),
  ('CRM-2177','TnT Management - CORP'),
  ('CRM-2182','Spartan Investment Group - CORP.'),
  ('CRM-2192','Elite-Stor Storage - CORP'),
  ('CRM-2211','Andover Properties - Storage King USA - CORP.'),
  ('CRM-2219','Andover Properties - Storage King USA - CORP.'),
  ('CRM-2233','National Storage Management - CORP'),
  ('CRM-2254','Mayflower Properties - Home Office'),
  ('CRM-2254','Prime Group Holdings, LLC - CORP'),
  ('CRM-23','National Storage Management - CORP'),
  ('CRM-23','Spartan Investment Group - CORP.'),
  ('CRM-24','Andover Properties - Storage King USA - CORP.'),
  ('CRM-24','National Storage Management - CORP'),
  ('CRM-24','New Crescendo LLC - CORP'),
  ('CRM-24','PS Canada Company, ULC - CORP'),
  ('CRM-24','Prime Group Holdings, LLC - CORP'),
  ('CRM-2440','Andover Properties - Storage King USA - CORP.'),
  ('CRM-2441','National Storage Management - CORP'),
  ('CRM-2454','Prime Group Holdings, LLC - CORP'),
  ('CRM-2499','Prime Group Holdings, LLC - CORP'),
  ('CRM-2511','National Storage Management - CORP'),
  ('CRM-2551','Andover Properties - Storage King USA - CORP.'),
  ('CRM-28','National Storage Management - CORP'),
  ('CRM-34','Prime Group Holdings, LLC - CORP'),
  ('CRM-36','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('CRM-36','National Storage Management - CORP'),
  ('CRM-36','Prime Group Holdings, LLC - CORP'),
  ('CRM-36','Spartan Investment Group - CORP.'),
  ('CRM-37','Andover Properties - Storage King USA - CORP.'),
  ('CRM-38','National Storage Management - CORP'),
  ('CRM-392','Andover Properties - Storage King USA - CORP.'),
  ('CRM-40','Andover Properties - Storage King USA - CORP.'),
  ('CRM-412','National Storage Management - CORP'),
  ('CRM-412','Prime Group Holdings, LLC - CORP'),
  ('CRM-429','Spartan Investment Group - CORP.'),
  ('CRM-433','National Storage Management - CORP'),
  ('CRM-6','Andover Properties - Storage King USA - CORP.'),
  ('CRM-7','Andover Properties - Storage King USA - CORP.'),
  ('CRM-7','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('CRM-7','National Storage Management - CORP'),
  ('CRM-7','New Crescendo LLC - CORP'),
  ('CRM-7','Prime Group Holdings, LLC - CORP'),
  ('CRM-7','Spartan Investment Group - CORP.'),
  ('DAT-2755','MyPlace Property Services LLC - CORP'),
  ('DAT-2757','Go Store It Management LLC - CORP'),
  ('DATA-1362','Otter Storage Management - CORP.'),
  ('DATA-1595','Andover Properties - Storage King USA - CORP.'),
  ('DATA-1616','Otter Storage Management - CORP.'),
  ('DATA-1616','SHS Development Company dba The Lock Up Self Storage - CORP.'),
  ('DATA-1616','West Coast Self-Storage - CORP.'),
  ('DATA-1617','West Coast Self-Storage - CORP.'),
  ('DATA-1629','StoreEase - CORP'),
  ('DATA-1639','Spartan Investment Group - CORP.'),
  ('DATA-1653','MyPlace Property Services LLC - CORP'),
  ('DATA-1672','SHS Development Company dba The Lock Up Self Storage - CORP.'),
  ('DATA-1694','SHS Development Company dba The Lock Up Self Storage - CORP.'),
  ('DATA-1695','10 Federal Storage - CORP.'),
  ('DATA-1818','MyPlace Property Services LLC - CORP'),
  ('DATA-1818','White Label Storage Management - CORP'),
  ('DATA-1822','National Storage Management - CORP'),
  ('DEVOPS-7963','West Coast Self-Storage - CORP.'),
  ('EDGE-102','Spartan Investment Group - CORP.'),
  ('EDGE-1115','West Coast Self-Storage - CORP.'),
  ('EDGE-112','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('EDGE-1255','West Coast Self-Storage - CORP.'),
  ('EDGE-1256','MyPlace Property Services LLC - CORP'),
  ('EDGE-1264','White Label Storage Management - CORP'),
  ('EDGE-147','White Label Storage Management - CORP'),
  ('EDGE-195','West Coast Self-Storage - CORP.'),
  ('EDGE-197','StoreEase - CORP'),
  ('EDGE-221','Attic Management Group - CORP'),
  ('EDGE-23','Attic Management Group - CORP'),
  ('EDGE-230','Mayflower Properties - Home Office'),
  ('EDGE-234','MyPlace Property Services LLC - CORP'),
  ('EDGE-248','West Coast Self-Storage - CORP.'),
  ('EDGE-281','National Storage Management - CORP'),
  ('EDGE-288','StoreEase - CORP'),
  ('EDGE-296','StoreEase - CORP'),
  ('EDGE-298','West Coast Self-Storage - CORP.'),
  ('EDGE-315','Go Store It Management LLC - CORP'),
  ('EDGE-328','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('EDGE-339','West Coast Self-Storage - CORP.'),
  ('EDGE-343','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('EDGE-351','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-351','The Storage Mall - CORP.'),
  ('EDGE-351','West Coast Self-Storage - CORP.'),
  ('EDGE-358','West Coast Self-Storage - CORP.'),
  ('EDGE-4050','West Coast Self-Storage - CORP.'),
  ('EDGE-4055','West Coast Self-Storage - CORP.'),
  ('EDGE-4060','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-4071','West Coast Self-Storage - CORP.'),
  ('EDGE-4072','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-4072','National Storage Management - CORP'),
  ('EDGE-4072','West Coast Self-Storage - CORP.'),
  ('EDGE-4072','White Label Storage Management - CORP'),
  ('EDGE-4073','National Storage Management - CORP'),
  ('EDGE-4107','White Label Storage Management - CORP'),
  ('EDGE-4147','The Storage Mall - CORP.'),
  ('EDGE-4148','The Storage Mall - CORP.'),
  ('EDGE-4153','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('EDGE-4187','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-4192','White Label Storage Management - CORP'),
  ('EDGE-4198','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-4200','White Label Storage Management - CORP'),
  ('EDGE-4205','West Coast Self-Storage - CORP.'),
  ('EDGE-4215','StoreEase - CORP'),
  ('EDGE-4220','Attic Management Group - CORP'),
  ('EDGE-4220','MyPlace Property Services LLC - CORP'),
  ('EDGE-4220','Spartan Investment Group - CORP.'),
  ('EDGE-4220','West Coast Self-Storage - CORP.'),
  ('EDGE-4230','West Coast Self-Storage - CORP.'),
  ('EDGE-4238','MyPlace Property Services LLC - CORP'),
  ('EDGE-4240','West Coast Self-Storage - CORP.'),
  ('EDGE-4247','10 Federal Storage - CORP.'),
  ('EDGE-4250','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-4253','10 Federal Storage - CORP.'),
  ('EDGE-4255','White Label Storage Management - CORP'),
  ('EDGE-4280','West Coast Self-Storage - CORP.'),
  ('EDGE-4285','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-4289','10 Federal Storage - CORP.'),
  ('EDGE-4301','West Coast Self-Storage - CORP.'),
  ('EDGE-4304','Spartan Investment Group - CORP.'),
  ('EDGE-4314','National Storage Management - CORP'),
  ('EDGE-4323','Spartan Investment Group - CORP.'),
  ('EDGE-4323','West Coast Self-Storage - CORP.'),
  ('EDGE-434','West Coast Self-Storage - CORP.'),
  ('EDGE-4358','National Storage Management - CORP'),
  ('EDGE-436','West Coast Self-Storage - CORP.'),
  ('EDGE-4360','West Coast Self-Storage - CORP.'),
  ('EDGE-4361','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('EDGE-4367','Go Store It Management LLC - CORP'),
  ('EDGE-4369','Attic Management Group - CORP'),
  ('EDGE-4371','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('EDGE-4376','10 Federal Storage - CORP.'),
  ('EDGE-4379','West Coast Self-Storage - CORP.'),
  ('EDGE-438','The Storage Mall - CORP.'),
  ('EDGE-4380','West Coast Self-Storage - CORP.'),
  ('EDGE-4383','Go Store It Management LLC - CORP'),
  ('EDGE-4384','West Coast Self-Storage - CORP.'),
  ('EDGE-4385','PS Canada Company, ULC - CORP'),
  ('EDGE-4389','National Storage Management - CORP'),
  ('EDGE-4394','Attic Management Group - CORP'),
  ('EDGE-4396','West Coast Self-Storage - CORP.'),
  ('EDGE-4397','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-4398','West Coast Self-Storage - CORP.'),
  ('EDGE-4399','West Coast Self-Storage - CORP.'),
  ('EDGE-4404','SHS Development Company dba The Lock Up Self Storage - CORP.'),
  ('EDGE-4405','Go Store It Management LLC - CORP'),
  ('EDGE-4407','White Label Storage Management - CORP'),
  ('EDGE-4410','West Coast Self-Storage - CORP.'),
  ('EDGE-4411','Go Store It Management LLC - CORP'),
  ('EDGE-4411','West Coast Self-Storage - CORP.'),
  ('EDGE-4435','West Coast Self-Storage - CORP.'),
  ('EDGE-4438','The Storage Mall - CORP.'),
  ('EDGE-4439','Go Store It Management LLC - CORP'),
  ('EDGE-4441','West Coast Self-Storage - CORP.'),
  ('EDGE-4443','Attic Management Group - CORP'),
  ('EDGE-4443','West Coast Self-Storage - CORP.'),
  ('EDGE-4444','PS Canada Company, ULC - CORP'),
  ('EDGE-4447','West Coast Self-Storage - CORP.'),
  ('EDGE-4448','Attic Management Group - CORP'),
  ('EDGE-4449','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-4449','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('EDGE-4449','National Storage Management - CORP'),
  ('EDGE-4449','The Storage Mall - CORP.'),
  ('EDGE-4452','West Coast Self-Storage - CORP.'),
  ('EDGE-4458','SHS Development Company dba The Lock Up Self Storage - CORP.'),
  ('EDGE-4458','Spartan Investment Group - CORP.'),
  ('EDGE-446','West Coast Self-Storage - CORP.'),
  ('EDGE-4460','West Coast Self-Storage - CORP.'),
  ('EDGE-4463','Go Store It Management LLC - CORP'),
  ('EDGE-4464','StoreEase - CORP'),
  ('EDGE-4464','West Coast Self-Storage - CORP.'),
  ('EDGE-4468','Spartan Investment Group - CORP.'),
  ('EDGE-4468','The Storage Mall - CORP.'),
  ('EDGE-4468','West Coast Self-Storage - CORP.'),
  ('EDGE-4469','National Storage Management - CORP'),
  ('EDGE-4470','West Coast Self-Storage - CORP.'),
  ('EDGE-4472','National Storage Management - CORP'),
  ('EDGE-4472','Spartan Investment Group - CORP.'),
  ('EDGE-4473','Attic Management Group - CORP'),
  ('EDGE-4475','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-4476','The Storage Mall - CORP.'),
  ('EDGE-4476','West Coast Self-Storage - CORP.'),
  ('EDGE-448','West Coast Self-Storage - CORP.'),
  ('EDGE-4487','West Coast Self-Storage - CORP.'),
  ('EDGE-449','West Coast Self-Storage - CORP.'),
  ('EDGE-4500','The Storage Mall - CORP.'),
  ('EDGE-4505','West Coast Self-Storage - CORP.'),
  ('EDGE-451','The Storage Mall - CORP.'),
  ('EDGE-4510','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('EDGE-4512','Attic Management Group - CORP'),
  ('EDGE-452','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('EDGE-4522','The Storage Mall - CORP.'),
  ('EDGE-4532','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-4532','National Storage Management - CORP'),
  ('EDGE-4533','Spartan Investment Group - CORP.'),
  ('EDGE-455','West Coast Self-Storage - CORP.'),
  ('EDGE-457','West Coast Self-Storage - CORP.'),
  ('EDGE-4570','MyPlace Property Services LLC - CORP'),
  ('EDGE-4594','National Storage Management - CORP'),
  ('EDGE-460','West Coast Self-Storage - CORP.'),
  ('EDGE-461','West Coast Self-Storage - CORP.'),
  ('EDGE-4610','West Coast Self-Storage - CORP.'),
  ('EDGE-4624','10 Federal Storage - CORP.'),
  ('EDGE-4629','West Coast Self-Storage - CORP.'),
  ('EDGE-4634','National Storage Management - CORP'),
  ('EDGE-4634','West Coast Self-Storage - CORP.'),
  ('EDGE-4634','White Label Storage Management - CORP'),
  ('EDGE-4635','National Storage Management - CORP'),
  ('EDGE-4635','West Coast Self-Storage - CORP.'),
  ('EDGE-464','West Coast Self-Storage - CORP.'),
  ('EDGE-4658','West Coast Self-Storage - CORP.'),
  ('EDGE-467','West Coast Self-Storage - CORP.'),
  ('EDGE-4672','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-4677','National Storage Management - CORP'),
  ('EDGE-4677','Otter Storage Management - CORP.'),
  ('EDGE-4677','West Coast Self-Storage - CORP.'),
  ('EDGE-470','Otter Storage Management - CORP.'),
  ('EDGE-473','West Coast Self-Storage - CORP.'),
  ('EDGE-475','West Coast Self-Storage - CORP.'),
  ('EDGE-4751','MyPlace Property Services LLC - CORP'),
  ('EDGE-4751','SHS Development Company dba The Lock Up Self Storage - CORP.'),
  ('EDGE-4751','West Coast Self-Storage - CORP.'),
  ('EDGE-4778','Attic Management Group - CORP'),
  ('EDGE-4778','National Storage Management - CORP'),
  ('EDGE-4781','MyPlace Property Services LLC - CORP'),
  ('EDGE-479','West Coast Self-Storage - CORP.'),
  ('EDGE-483','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-4833','West Coast Self-Storage - CORP.'),
  ('EDGE-484','West Coast Self-Storage - CORP.'),
  ('EDGE-4846','StoreEase - CORP'),
  ('EDGE-488','West Coast Self-Storage - CORP.'),
  ('EDGE-489','West Coast Self-Storage - CORP.'),
  ('EDGE-495','West Coast Self-Storage - CORP.'),
  ('EDGE-501','West Coast Self-Storage - CORP.'),
  ('EDGE-502','West Coast Self-Storage - CORP.'),
  ('EDGE-506','West Coast Self-Storage - CORP.'),
  ('EDGE-507','West Coast Self-Storage - CORP.'),
  ('EDGE-511','West Coast Self-Storage - CORP.'),
  ('EDGE-513','West Coast Self-Storage - CORP.'),
  ('EDGE-516','West Coast Self-Storage - CORP.'),
  ('EDGE-518','West Coast Self-Storage - CORP.'),
  ('EDGE-524','West Coast Self-Storage - CORP.'),
  ('EDGE-534','SHS Development Company dba The Lock Up Self Storage - CORP.'),
  ('EDGE-534','West Coast Self-Storage - CORP.'),
  ('EDGE-541','The Storage Mall - CORP.'),
  ('EDGE-546','Attic Management Group - CORP'),
  ('EDGE-554','Spartan Investment Group - CORP.'),
  ('EDGE-556','10 Federal Storage - CORP.'),
  ('EDGE-556','Spartan Investment Group - CORP.'),
  ('EDGE-556','White Label Storage Management - CORP'),
  ('EDGE-558','Spartan Investment Group - CORP.'),
  ('EDGE-577','Otter Storage Management - CORP.'),
  ('EDGE-595','National Storage Management - CORP'),
  ('EDGE-596','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-600','Attic Management Group - CORP'),
  ('EDGE-607','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('EDGE-608','Attic Management Group - CORP'),
  ('EDGE-613','The Storage Mall - CORP.'),
  ('EDGE-616','The Storage Mall - CORP.'),
  ('EDGE-617','The Storage Mall - CORP.'),
  ('EDGE-618','Spartan Investment Group - CORP.'),
  ('EDGE-620','Otter Storage Management - CORP.'),
  ('EDGE-623','Go Store It Management LLC - CORP'),
  ('EDGE-623','West Coast Self-Storage - CORP.'),
  ('EDGE-624','Go Store It Management LLC - CORP'),
  ('EDGE-624','Spartan Investment Group - CORP.'),
  ('EDGE-629','National Storage Management - CORP'),
  ('EDGE-634','Attic Management Group - CORP'),
  ('EDGE-635','Go Store It Management LLC - CORP'),
  ('EDGE-642','Attic Management Group - CORP'),
  ('EDGE-647','10 Federal Storage - CORP.'),
  ('EDGE-652','Go Store It Management LLC - CORP'),
  ('EDGE-653','Go Store It Management LLC - CORP'),
  ('EDGE-654','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-657','Attic Management Group - CORP'),
  ('EDGE-81','Go Store It Management LLC - CORP'),
  ('EDGE-95','Andover Properties - Storage King USA - CORP.'),
  ('EDGE-98','Clark Properties (All Aboard Storage) - CORP. OFFICE'),
  ('EDGE-98','West Coast Self-Storage - CORP.'),
  ('ESST-738','West Coast Self-Storage - CORP.'),
  ('MDEV-14396','Go Store It Management LLC - CORP'),
  ('PAY-4616','National Storage Management - CORP'),
  ('PAY-4954','Elite-Stor Storage - CORP'),
  ('PAY-4954','Prime Group Holdings, LLC - CORP'),
  ('PAY-4954','SecureSpace Management LLC - CORP'),
  ('PAY-5190','National Storage Management - CORP'),
  ('PAY-5310','National Storage Management - CORP'),
  ('PAY-5590','Storage Asset Management - CORP'),
  ('PAY-5936','National Storage Management - CORP'),
  ('PAY-6315','PS Canada Company, ULC - CORP'),
  ('PAY-6328','Attic Management Group - CORP'),
  ('PAY-6328','Recreational Realty - CORP'),
  ('PAY-6328','SecureSpace Management LLC - CORP'),
  ('PAY-6328','Storage Asset Management - CORP'),
  ('PAY-6328','TnT Management - CORP'),
  ('PAY-6328','White Label Storage Management - CORP'),
  ('PAY-6663','West Coast Self-Storage - CORP.'),
  ('PAY-6666','The Storage Mall - CORP.'),
  ('PAY-6827','MyPlace Property Services LLC - CORP'),
  ('PAY-6883','PS Canada Company, ULC - CORP'),
  ('PAY-6974','StoreEase - CORP'),
  ('PAY-6975','PS Canada Company, ULC - CORP'),
  ('PAY-6975','West Coast Self-Storage - CORP.'),
  ('PAY-6977','West Coast Self-Storage - CORP.'),
  ('PAY-7035','SHS Development Company dba The Lock Up Self Storage - CORP.'),
  ('PAY-7107','Storage Asset Management - CORP'),
  ('PAY-7272','Elite-Stor Storage - CORP'),
  ('PAY-7294','Prime Group Holdings, LLC - CORP'),
  ('PAY-7429','Prime Group Holdings, LLC - CORP'),
  ('PAYEXT-33','Spartan Investment Group - CORP.'),
  ('PAYEXT-54','The Storage Mall - CORP.'),
  ('PAYEXT-54','West Coast Self-Storage - CORP.'),
  ('PAYEXT-55','National Storage Management - CORP'),
  ('POL-1413','10 Federal Storage - CORP.'),
  ('POL-854','Recreational Realty - CORP'),
  ('POL-854','Storage Asset Management - CORP'),
  ('SF-17669','Elite-Stor Storage - CORP'),
  ('SF-17669','Storage Asset Management - CORP'),
  ('SF-18494','Right Move Storage - CORP'),
  ('SF-18656','Andover Properties - Storage King USA - CORP.'),
  ('SF-19232','Storage Asset Management - CORP'),
  ('SFT-10926','Go Store It Management LLC - CORP'),
  ('SL-13184','SecureSpace Management LLC - CORP'),
  ('SL-15404','SecureSpace Management LLC - CORP'),
  ('SL-15529','TnT Management - CORP'),
  ('SL-15763','Storage Asset Management - CORP'),
  ('SL-16259','Recreational Realty - CORP'),
  ('SL-16341','New Crescendo LLC - CORP'),
  ('SL-16476','TnT Management - CORP'),
  ('SL-16660','Andover Properties - Storage King USA - CORP.'),
  ('SL-16660','Prime Group Holdings, LLC - CORP'),
  ('SL-16660','SecureSpace Management LLC - CORP'),
  ('SL-16660','Storage Asset Management - CORP'),
  ('SL-16660','TnT Management - CORP'),
  ('SL-17041','Elite-Stor Storage - CORP'),
  ('SL-17121','Storage Asset Management - CORP'),
  ('SL-17490','SecureSpace Management LLC - CORP'),
  ('SL-17544','White Label Storage Management - CORP'),
  ('SL-17737','Storage Asset Management - CORP'),
  ('SL-17774','Prime Group Holdings, LLC - CORP'),
  ('SL-17815','Elite-Stor Storage - CORP'),
  ('SL-18161','New Crescendo LLC - CORP'),
  ('SL-18161','TnT Management - CORP'),
  ('SL-18162','Andover Properties - Storage King USA - CORP.'),
  ('SL-18289','Elite-Stor Storage - CORP'),
  ('SL-18341','Storage Asset Management - CORP'),
  ('SL-18385','Elite-Stor Storage - CORP'),
  ('SL-18404','Prime Group Holdings, LLC - CORP'),
  ('SL-18414','Elite-Stor Storage - CORP'),
  ('SL-18415','Storage Asset Management - CORP'),
  ('SL-18515','Prime Group Holdings, LLC - CORP'),
  ('SL-18560','Prime Group Holdings, LLC - CORP'),
  ('SL-18656','Storage Asset Management - CORP'),
  ('SL-18867','SecureSpace Management LLC - CORP'),
  ('SL-18966','Storage Asset Management - CORP'),
  ('SL-19095','Recreational Realty - CORP'),
  ('SL-19193','Storage Asset Management - CORP'),
  ('SL-19425','Prime Group Holdings, LLC - CORP'),
  ('SL-19751','SecureSpace Management LLC - CORP'),
  ('SL-19850','Elite-Stor Storage - CORP'),
  ('SL-19850','Prime Group Holdings, LLC - CORP'),
  ('SL-19850','Storage Asset Management - CORP'),
  ('SL-20195','Storage Asset Management - CORP'),
  ('SL-20209','Prime Group Holdings, LLC - CORP'),
  ('SL-20209','TnT Management - CORP'),
  ('SL-20214','Prime Group Holdings, LLC - CORP'),
  ('SL-20235','Prime Group Holdings, LLC - CORP'),
  ('SL-20250','Storage Asset Management - CORP'),
  ('SL-20272','Right Move Storage - CORP'),
  ('SL-20273','Storage Asset Management - CORP'),
  ('SL-20303','TnT Management - CORP'),
  ('SL-20478','Storage Asset Management - CORP'),
  ('SL-20518','Recreational Realty - CORP'),
  ('SL-20519','Prime Group Holdings, LLC - CORP'),
  ('SL-20574','Elite-Stor Storage - CORP'),
  ('SL-20798','SecureSpace Management LLC - CORP'),
  ('SL-20811','SecureSpace Management LLC - CORP'),
  ('SL-20959','TnT Management - CORP'),
  ('SL-5446','Andover Properties - Storage King USA - CORP.'),
  ('SLT-8232','Andover Properties - Storage King USA - CORP.'),
  ('SLT-9180','Storage Asset Management - CORP'),
  ('SLT-9360','SecureSpace Management LLC - CORP'),
  ('SLT-9363','Elite-Stor Storage - CORP'),
  ('SLT-9381','Elite-Stor Storage - CORP'),
  ('SLT-9395','Prime Group Holdings, LLC - CORP'),
  ('SLT-9411','Prime Group Holdings, LLC - CORP'),
  ('SLT-9425','Elite-Stor Storage - CORP'),
  ('SLT-9426','Elite-Stor Storage - CORP'),
  ('SLT-9426','White Label Storage Management - CORP'),
  ('SLT-9469','New Crescendo LLC - CORP'),
  ('SLT-9473','Storage Asset Management - CORP'),
  ('WA-1238','10 Federal Storage - CORP.'),
  ('WA-1238','Spartan Investment Group - CORP.'),
  ('WA-1431','Spartan Investment Group - CORP.'),
  ('WA-1476','National Storage Management - CORP'),
  ('WA-1746','Prime Group Holdings, LLC - CORP'),
  ('WA-1819','10 Federal Storage - CORP.'),
  ('WA-1820','10 Federal Storage - CORP.'),
  ('WA-1826','Spartan Investment Group - CORP.'),
  ('WA-1840','National Storage Management - CORP'),
  ('WA-1885','10 Federal Storage - CORP.'),
  ('WEB-7981','Storage Asset Management - CORP'),
  ('WEB-8152','Andover Properties - Storage King USA - CORP.'),
  ('WEB-8152','Storage Asset Management - CORP'),
  ('WEB-8265','Spartan Investment Group - CORP.')
) AS looker(jira_key, sf_account_name)
JOIN jira_issues ji ON ji.jira_key = looker.jira_key
JOIN accounts a ON a.name = looker.sf_account_name AND a.user_id = ji.user_id
ON CONFLICT (account_id, jira_issue_id) DO UPDATE
  SET match_type = 'looker_export',
      match_confidence = 1.0;
